#!/usr/bin/env python3
"""
Froala Editor 3.2.0 HTML Chunker v2 for RAG / Search Indexing
==============================================================

Parses HTML generated by Froala Editor 3.2.0, producing semantically
meaningful chunks with heading-path context, data-table row expansion,
and layout-table linearisation.

Key improvements over v1
------------------------
- Heading text no longer duplicated in embedding_text
- Layout-table cells propagate internal headings into heading_path
- dom_path tracked in metadata
- BR-paragraph restoration preserves inline markup
- classify_table excludes nested-table signals via _find_own()
- Robust error handling throughout

Dependencies: beautifulsoup4, lxml
"""

from __future__ import annotations

import html as html_mod
import re
import uuid
from dataclasses import dataclass, field
from typing import Any

from bs4 import BeautifulSoup, Comment, NavigableString, Tag

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  1. Data Structures
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


@dataclass
class ParseConfig:
    """Knobs for the chunker."""

    target_tokens: int = 400
    max_tokens: int = 550
    min_tokens: int = 120
    keep_html: bool = True
    detect_layout_tables: bool = True
    split_on_paragraph_only: bool = True


@dataclass
class Chunk:
    """A single chunk produced by the chunker."""

    chunk_id: str
    doc_id: str
    chunk_type: str  # section | data_table_section | data_table_row | layout_region
    heading_path: list[str]
    embedding_text: str
    cleaned_html: str
    plain_text: str
    metadata: dict[str, Any] = field(default_factory=dict)


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  2. Constants & Tiny Helpers
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

HEADING_TAGS = frozenset({"h1", "h2", "h3", "h4", "h5", "h6"})
BLOCK_TAGS = HEADING_TAGS | frozenset(
    {
        "p", "div", "ul", "ol", "li", "pre", "blockquote",
        "table", "img", "hr", "figure", "figcaption",
        "section", "article", "header", "footer", "nav", "aside", "main",
        "details", "summary", "dl", "dt", "dd",
    }
)
REMOVE_TAGS = frozenset({"script", "style", "noscript", "template", "iframe"})


def _uid() -> str:
    return uuid.uuid4().hex[:12]


def estimate_tokens(text: str) -> int:
    """Rough token count for mixed Korean / English text (~4 chars/token)."""
    if not text:
        return 0
    return max(1, len(text) // 4)


def _heading_level(name: str) -> int:
    """Return 1–6 for h1–h6, else 0."""
    if name and name.lower() in HEADING_TAGS:
        return int(name[1])
    return 0


def _tag_text(tag: Tag) -> str:
    """Visible text, whitespace-normalised."""
    return re.sub(r"\s+", " ", tag.get_text(separator=" ")).strip()


def _tag_html(tag: Tag) -> str:
    return str(tag)


def _dom_path(tag: Tag) -> str:
    """Build a CSS-like DOM path for debugging, e.g. 'html>body>div>table>tr>td'."""
    parts: list[str] = []
    node = tag
    while node and isinstance(node, Tag):
        parts.append(node.name)
        node = node.parent  # type: ignore[assignment]
    parts.reverse()
    return ">".join(parts)


def _heading_prefix(heading_path: list[str]) -> str:
    """Build the heading-path string for embedding_text."""
    return "\n".join(heading_path)


def _normalise_ws(text: str) -> str:
    return re.sub(r"[ \t]+", " ", text).strip()


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  3. HTML Sanitisation & Froala Normalisation
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


def sanitize_and_normalize_html(html_str: str) -> BeautifulSoup:
    """Parse raw HTML, extract <body> if present, strip junk tags.

    Returns a BeautifulSoup tree wrapped in a single <div> container.
    """
    soup = BeautifulSoup(html_str, "lxml")

    # Extract body content (Froala fullPage mode)
    body = soup.find("body")
    source = body if body else soup

    wrapper = BeautifulSoup("<div id='_root'></div>", "lxml").find("div")
    assert wrapper is not None
    for child in list(source.children):
        wrapper.append(child.extract())

    new_soup = BeautifulSoup(str(wrapper), "lxml")

    # Strip unwanted tags
    for name in REMOVE_TAGS:
        for tag in new_soup.find_all(name):
            tag.decompose()

    # Strip HTML comments
    for c in new_soup.find_all(string=lambda t: isinstance(t, Comment)):
        c.extract()

    return new_soup


def normalize_froala_structure(soup: BeautifulSoup) -> BeautifulSoup:
    """Froala 3.2.x specific normalisation.

    - Convert double-<br> into <p> boundaries
    - Remove empty tags
    - Normalise whitespace
    """
    _convert_double_br(soup)
    _strip_empty_tags(soup)
    # Normalise whitespace in text nodes (skip <pre>/<code>)
    for tn in soup.find_all(string=True):
        if tn.parent and tn.parent.name in ("pre", "code"):
            continue
        cleaned = _normalise_ws(str(tn))
        if cleaned != str(tn):
            tn.replace_with(cleaned)
    return soup


# -- helpers --------------------------------------------------------


def _strip_empty_tags(soup: BeautifulSoup) -> None:
    """Remove tags with no visible content (preserve void elements)."""
    VOID = frozenset({"br", "hr", "img", "input", "col", "embed", "source", "wbr"})
    changed = True
    while changed:
        changed = False
        for tag in soup.find_all(True):
            if tag.name in VOID:
                continue
            if not tag.get_text(strip=True) and not tag.find(list(VOID)):
                tag.decompose()
                changed = True


def _convert_double_br(soup: BeautifulSoup) -> None:
    """Within block parents, turn consecutive <br><br> into <p> splits.

    Preserves inline markup inside the resulting paragraphs.
    """
    SKIP = frozenset({"pre", "code", "table", "thead", "tbody", "tfoot", "tr", "td", "th"})
    for parent in list(soup.find_all(True)):
        if parent.name in SKIP:
            continue
        if not _has_double_br(parent):
            continue
        _split_on_double_br(parent, soup)


def _has_double_br(parent: Tag) -> bool:
    run = 0
    for child in parent.children:
        if isinstance(child, Tag) and child.name == "br":
            run += 1
            if run >= 2:
                return True
        elif isinstance(child, NavigableString) and not str(child).strip():
            continue  # whitespace between <br>s
        else:
            run = 0
    return False


def _split_on_double_br(parent: Tag, soup: BeautifulSoup) -> None:
    """Replace children of *parent* with <p> wrappers split at double-<br>."""
    children = list(parent.children)

    segments: list[list] = [[]]
    br_run = 0
    pending_single_br = False

    for child in children:
        if isinstance(child, Tag) and child.name == "br":
            br_run += 1
            if br_run >= 2:
                # Start new segment
                if segments[-1]:
                    segments.append([])
                br_run = 0
                pending_single_br = False
            continue
        # whitespace-only NavigableString between <br>s → don't reset run
        if isinstance(child, NavigableString) and not str(child).strip():
            if br_run >= 1:
                continue
        # Real content
        if br_run == 1:
            # single <br> → just a line break within segment
            segments[-1].append(soup.new_tag("br"))
        br_run = 0
        segments[-1].append(child.extract() if hasattr(child, "extract") else child)

    if len(segments) <= 1:
        return

    # Remove all old children
    parent.clear()

    for seg in segments:
        if not seg:
            continue
        p = soup.new_tag("p")
        for item in seg:
            p.append(item)
        parent.append(p)


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  4. Table Classification
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


def _find_own(table_tag: Tag, names: str | list[str], **kw: Any) -> list[Tag]:
    """Find elements belonging directly to *this* table, not nested ones."""
    result: list[Tag] = []
    if isinstance(names, str):
        names = [names]
    for el in table_tag.find_all(names, recursive=True, **kw):
        if el.find_parent("table") is table_tag:
            result.append(el)
    return result


def classify_table(table_tag: Tag) -> tuple[str, dict]:
    """Classify a <table> as ``'data'``, ``'layout'``, or ``'unknown'``.

    Only inspects elements that belong directly to this table (not
    nested <table> descendants).

    Returns ``(kind, reason_dict)`` with scoring details.
    """
    reason: dict[str, Any] = {}

    # ── signals (own only) ─────────────────────────────────────────
    has_caption = bool(_find_own(table_tag, "caption"))
    has_thead = bool(_find_own(table_tag, "thead"))
    own_ths = _find_own(table_tag, "th")
    has_th = bool(own_ths)
    has_scope = any(t.get("scope") for t in own_ths)
    has_headers_attr = bool(_find_own(table_tag, ["td", "th"], attrs={"headers": True}))

    role = (table_tag.get("role") or "").lower()
    presentation_role = role in ("presentation", "none")

    nested_tables = len(table_tag.find_all("table", recursive=True))

    all_text = _tag_text(table_tag)
    links = table_tag.find_all("a", recursive=True)
    link_text_len = sum(len(_tag_text(a)) for a in links)
    link_density = link_text_len / max(len(all_text), 1)

    own_rows = _find_own(table_tag, "tr")
    col_counts = [len(r.find_all(["td", "th"], recursive=False)) for r in own_rows]
    uniform_cols = len(set(col_counts)) <= 1 and len(col_counts) > 1

    imgs = table_tag.find_all("img", recursive=True)
    forms = table_tag.find_all(["input", "button", "select", "textarea"], recursive=True)
    interactive = len(imgs) + len(forms) + len(links)
    own_cells = _find_own(table_tag, ["td", "th"])
    total_cells = len(own_cells)

    reason.update(
        {
            "has_caption": has_caption,
            "has_th": has_th,
            "has_thead": has_thead,
            "has_scope": has_scope,
            "has_headers_attr": has_headers_attr,
            "presentation_role": presentation_role,
            "link_density": round(link_density, 3),
            "nested_tables": nested_tables,
            "row_count": len(col_counts),
            "uniform_columns": uniform_cols,
            "interactive_elements": interactive,
            "total_cells": total_cells,
        }
    )

    # ── scoring ────────────────────────────────────────────────────
    ds = 0.0  # data_score
    ls = 0.0  # layout_score

    if has_caption:
        ds += 0.25
    if has_th:
        ds += 0.20
    if has_thead:
        ds += 0.20
    if has_scope:
        ds += 0.15
    if has_headers_attr:
        ds += 0.10
    if uniform_cols and len(col_counts) >= 2:
        ds += 0.10

    if presentation_role:
        ls += 0.35
    if nested_tables > 0:
        ls += 0.15
    if link_density > 0.5:
        ls += 0.15
    if 0 < total_cells <= 3:
        ls += 0.10
    if interactive > 3 and total_cells > 0:
        ls += 0.10

    # edge: presentation + data signals → pull toward unknown
    if presentation_role and (has_th or has_caption):
        ls -= 0.15
        ds += 0.10

    if ds > ls and ds >= 0.30:
        kind = "data"
        conf = min(1.0, ds / max(ds + ls, 0.01))
    elif ls > ds and ls >= 0.20:
        kind = "layout"
        conf = min(1.0, ls / max(ds + ls, 0.01))
    else:
        kind = "unknown"
        conf = 0.30

    reason.update(
        {
            "data_score": round(ds, 3),
            "layout_score": round(ls, 3),
            "estimated_kind": kind,
            "confidence": round(conf, 3),
        }
    )
    return kind, reason


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  5. Block Extraction (recursive DOM walk)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


def extract_blocks(
    node: Tag,
    heading_state: dict[str, list],
    config: ParseConfig,
    dom_prefix: str = "",
) -> list[dict]:
    """Recursively walk the DOM and return a flat list of *block dicts*.

    Block dict keys:
        type:          heading | paragraph | list | table | image |
                       preformatted | blockquote
        tag:           original Tag (or None for bare text)
        text:          plain text
        html:          cleaned HTML
        heading_path:  current heading breadcrumb
        dom_path:      CSS-like path
        level:         heading level (headings only)
    """
    blocks: list[dict] = []

    if isinstance(node, NavigableString):
        text = str(node).strip()
        if text:
            blocks.append(_block("paragraph", None, text, html_mod.escape(text), heading_state, dom_prefix))
        return blocks

    if not isinstance(node, Tag):
        return blocks

    name = (node.name or "").lower()
    path = f"{dom_prefix}>{name}" if dom_prefix else name

    if name in REMOVE_TAGS:
        return blocks

    # ── heading ────────────────────────────────────────────────────
    if name in HEADING_TAGS:
        level = _heading_level(name)
        text = _tag_text(node)
        if text:
            _update_heading_state(heading_state, level, text)
            blocks.append(
                _block("heading", node, text, _tag_html(node), heading_state, path, level=level)
            )
        return blocks

    # ── table ──────────────────────────────────────────────────────
    if name == "table":
        blocks.append(_block("table", node, _tag_text(node), _tag_html(node), heading_state, path))
        return blocks

    # ── img ─────────────────────────────────────────────────────────
    if name == "img":
        alt = node.get("alt", "")
        blocks.append(
            _block("image", node, f"[Image: {alt}]" if alt else "[Image]", _tag_html(node), heading_state, path)
        )
        return blocks

    # ── pre ─────────────────────────────────────────────────────────
    if name == "pre":
        blocks.append(_block("preformatted", node, node.get_text(), _tag_html(node), heading_state, path))
        return blocks

    # ── blockquote ──────────────────────────────────────────────────
    if name == "blockquote":
        blocks.append(_block("blockquote", node, _tag_text(node), _tag_html(node), heading_state, path))
        return blocks

    # ── list ────────────────────────────────────────────────────────
    if name in ("ul", "ol"):
        blocks.append(_block("list", node, _tag_text(node), _tag_html(node), heading_state, path))
        return blocks

    # ── paragraph ──────────────────────────────────────────────────
    if name == "p":
        text = _tag_text(node)
        if text:
            blocks.append(_block("paragraph", node, text, _tag_html(node), heading_state, path))
        return blocks

    # ── div: container vs leaf ─────────────────────────────────────
    if name == "div":
        has_block_child = any(isinstance(c, Tag) and c.name in BLOCK_TAGS for c in node.children)
        if has_block_child:
            for child in node.children:
                blocks.extend(extract_blocks(child, heading_state, config, path))
        else:
            text = _tag_text(node)
            if text:
                blocks.append(_block("paragraph", node, text, _tag_html(node), heading_state, path))
        return blocks

    # ── fallback: recurse ──────────────────────────────────────────
    for child in node.children:
        blocks.extend(extract_blocks(child, heading_state, config, path))

    return blocks


def _block(
    btype: str,
    tag: Tag | None,
    text: str,
    html_str: str,
    hs: dict,
    dom_path: str,
    *,
    level: int = 0,
) -> dict:
    d: dict[str, Any] = {
        "type": btype,
        "tag": tag,
        "text": text,
        "html": html_str,
        "heading_path": list(hs["path"]),
        "dom_path": dom_path,
    }
    if level:
        d["level"] = level
    return d


def _update_heading_state(hs: dict[str, list], level: int, text: str) -> None:
    """Trim the heading stack and push the new heading."""
    while hs["levels"] and hs["levels"][-1] >= level:
        hs["path"].pop()
        hs["levels"].pop()
    hs["path"].append(f"[H{level}] {text}")
    hs["levels"].append(level)


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  6. Section Chunking
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


def chunk_sections(
    blocks: list[dict],
    doc_id: str,
    config: ParseConfig,
) -> list[Chunk]:
    """Turn extracted blocks into Chunks. Tables are delegated out."""
    chunks: list[Chunk] = []
    buf: list[dict] = []
    order = 0

    def flush() -> None:
        nonlocal buf, order
        if not buf:
            return
        new = _build_section_chunks(buf, doc_id, config, order)
        chunks.extend(new)
        order += len(new)
        buf = []

    for blk in blocks:
        if blk["type"] == "table":
            flush()
            tc = _process_table(blk["tag"], blk["heading_path"], doc_id, config, order)
            chunks.extend(tc)
            order += len(tc)
            continue

        if blk["type"] == "heading":
            flush()

        buf.append(blk)

        # budget check
        buf_text = "\n".join(b["text"] for b in buf if b["type"] != "heading")
        if estimate_tokens(buf_text) >= config.max_tokens:
            flush()

    flush()
    return chunks


def _build_section_chunks(
    blocks: list[dict],
    doc_id: str,
    config: ParseConfig,
    start_order: int,
) -> list[Chunk]:
    """Convert a contiguous run of blocks into ≥1 section Chunk(s),
    splitting at block boundaries when the token budget overflows.

    Headings contribute to heading_path / metadata but are **not**
    repeated as body text (avoids duplication).
    """
    if not blocks:
        return []

    hp = blocks[0].get("heading_path", [])

    # Separate heading blocks from body blocks
    body = [b for b in blocks if b["type"] != "heading"]
    if not body:
        # heading-only section (e.g. heading with no following content yet)
        return []

    all_text = "\n".join(b["text"] for b in body)
    all_html = "\n".join(b.get("html", "") for b in body)
    btypes = list({b["type"] for b in body})
    dom_paths = [b.get("dom_path", "") for b in body if b.get("dom_path")]

    tok = estimate_tokens(all_text)
    if tok <= config.max_tokens:
        return [_make_section(hp, all_text, all_html, btypes, dom_paths, doc_id, start_order)]

    # ── split at block boundaries ──────────────────────────────────
    result: list[Chunk] = []
    sub: list[dict] = []
    sub_tok = 0

    for b in body:
        bt = estimate_tokens(b["text"])
        if sub and sub_tok + bt > config.max_tokens:
            result.append(
                _make_section(
                    hp,
                    "\n".join(s["text"] for s in sub),
                    "\n".join(s.get("html", "") for s in sub),
                    list({s["type"] for s in sub}),
                    [s.get("dom_path", "") for s in sub if s.get("dom_path")],
                    doc_id,
                    start_order + len(result),
                )
            )
            sub, sub_tok = [], 0
        sub.append(b)
        sub_tok += bt

    if sub:
        result.append(
            _make_section(
                hp,
                "\n".join(s["text"] for s in sub),
                "\n".join(s.get("html", "") for s in sub),
                list({s["type"] for s in sub}),
                [s.get("dom_path", "") for s in sub if s.get("dom_path")],
                doc_id,
                start_order + len(result),
            )
        )
    return result


def _make_section(
    hp: list[str],
    text: str,
    html_str: str,
    btypes: list[str],
    dom_paths: list[str],
    doc_id: str,
    order: int,
) -> Chunk:
    prefix = _heading_prefix(hp)
    embed = f"{prefix}\n\n{text}".strip() if prefix else text
    return Chunk(
        chunk_id=f"{doc_id}_{_uid()}",
        doc_id=doc_id,
        chunk_type="section",
        heading_path=hp,
        embedding_text=embed,
        cleaned_html=html_str,
        plain_text=text,
        metadata={
            "block_types": btypes,
            "token_estimate": estimate_tokens(text),
            "source_order": order,
            "dom_path": dom_paths[:3] if dom_paths else [],
        },
    )


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  7. Table Router
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


def _process_table(
    table_tag: Tag,
    heading_path: list[str],
    doc_id: str,
    config: ParseConfig,
    start_order: int,
) -> list[Chunk]:
    """Classify and dispatch to the correct table parser."""
    if not config.detect_layout_tables:
        return parse_data_table(table_tag, heading_path, doc_id, config)

    kind, reason = classify_table(table_tag)

    if kind == "data":
        chunks = parse_data_table(table_tag, heading_path, doc_id, config)
    elif kind == "layout":
        chunks = parse_layout_table(table_tag, heading_path, doc_id, config)
    else:
        chunks = parse_layout_table(table_tag, heading_path, doc_id, config)
        for c in chunks:
            c.metadata["table_kind"] = "unknown"

    for i, c in enumerate(chunks):
        c.metadata.setdefault("table_kind", kind)
        c.metadata["table_confidence"] = reason["confidence"]
        c.metadata["classification_reason"] = reason
        c.metadata.setdefault("source_order", start_order + i)
    return chunks


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  8. Data Table Parser
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


def parse_data_table(
    table_tag: Tag,
    heading_path: list[str],
    doc_id: str,
    config: ParseConfig,
) -> list[Chunk]:
    """Parse a data table into one summary chunk + one chunk per body row.

    Each row chunk repeats the column headers so it is self-contained.
    """
    chunks: list[Chunk] = []
    prefix = _heading_prefix(heading_path)

    # caption
    cap_tag = table_tag.find("caption")
    caption = _tag_text(cap_tag) if cap_tag else ""

    # headers
    headers = _extract_headers(table_tag)

    # body rows (skip header-only rows)
    data_rows = _extract_data_rows(table_tag, headers)

    # ── summary chunk ──────────────────────────────────────────────
    lines: list[str] = []
    if prefix:
        lines.append(prefix)
    lines.append(f"[Table] {caption}" if caption else "[Table]")
    if headers:
        lines.append("[Headers] " + " | ".join(headers))
    for i, cells in enumerate(data_rows[:5]):
        lines.append("[Row] " + " | ".join(cells))
    if len(data_rows) > 5:
        lines.append(f"... ({len(data_rows)} rows total)")
    summary_text = "\n".join(lines)

    chunks.append(
        Chunk(
            chunk_id=f"{doc_id}_{_uid()}",
            doc_id=doc_id,
            chunk_type="data_table_section",
            heading_path=heading_path,
            embedding_text=summary_text,
            cleaned_html=_tag_html(table_tag),
            plain_text=_tag_text(table_tag),
            metadata={
                "block_types": ["table"],
                "has_table": True,
                "table_kind": "data",
                "caption": caption,
                "headers": headers,
                "row_count": len(data_rows),
                "token_estimate": estimate_tokens(summary_text),
                "dom_path": _dom_path(table_tag),
            },
        )
    )

    # ── per-row chunks ─────────────────────────────────────────────
    for idx, cells in enumerate(data_rows):
        rlines: list[str] = []
        if prefix:
            rlines.append(prefix)
        if caption:
            rlines.append(f"[Table] {caption}")
        if headers:
            rlines.append("[Headers] " + " | ".join(headers))
        if headers and len(headers) == len(cells):
            rlines.append("[Row] " + " | ".join(f"{h}: {v}" for h, v in zip(headers, cells)))
        else:
            rlines.append("[Row] " + " | ".join(cells))
        row_text = "\n".join(rlines)

        chunks.append(
            Chunk(
                chunk_id=f"{doc_id}_{_uid()}",
                doc_id=doc_id,
                chunk_type="data_table_row",
                heading_path=heading_path,
                embedding_text=row_text,
                cleaned_html="",  # individual row HTML not critical
                plain_text=" | ".join(cells),
                metadata={
                    "block_types": ["table_row"],
                    "has_table": True,
                    "table_kind": "data",
                    "row_index": idx,
                    "headers": headers,
                    "caption": caption,
                    "token_estimate": estimate_tokens(row_text),
                },
            )
        )

    return chunks


def _extract_headers(table_tag: Tag) -> list[str]:
    """Get column headers from <thead> or the first <th>-only row."""
    thead = table_tag.find("thead")
    if thead:
        hrow = thead.find("tr")
        if hrow:
            return [_tag_text(c) for c in hrow.find_all(["th", "td"], recursive=False)]
    first_row = table_tag.find("tr")
    if first_row:
        ths = first_row.find_all("th", recursive=False)
        if ths and len(ths) == len(first_row.find_all(["th", "td"], recursive=False)):
            return [_tag_text(th) for th in ths]
    return []


def _extract_data_rows(table_tag: Tag, headers: list[str]) -> list[list[str]]:
    """Return body rows as lists of cell strings, skipping the header row."""
    tbody = table_tag.find("tbody")
    parent = tbody if tbody else table_tag
    rows: list[list[str]] = []
    for tr in parent.find_all("tr", recursive=False):
        cells = tr.find_all(["td", "th"], recursive=False)
        texts = [_tag_text(c) for c in cells]
        # skip if this looks like the header row
        if headers and texts == headers:
            continue
        # skip all-th rows (likely a repeated header)
        if all(c.name == "th" for c in cells) and headers:
            continue
        rows.append(texts)
    return rows


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  9. Layout Table Parser
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


def parse_layout_table(
    table_tag: Tag,
    heading_path: list[str],
    doc_id: str,
    config: ParseConfig,
) -> list[Chunk]:
    """Linearise a layout table.  Does NOT produce row/column chunks.

    Instead, each top-level cell's content is extracted in DOM order
    as a ``layout_region`` chunk.  Nested tables are recursively
    classified.
    """
    chunks: list[Chunk] = []

    # Find cells belonging directly to this table
    top_cells: list[Tag] = [
        cell
        for cell in table_tag.find_all(["td", "th"], recursive=True)
        if cell.find_parent("table") is table_tag
    ]

    for ci, cell in enumerate(top_cells):
        nested = cell.find_all("table", recursive=False)

        # Always detect cell-level headings first
        cell_hp = _detect_cell_headings(cell, heading_path)

        if nested:
            # For each nested table, build a heading_path from headings
            # that appear before that table in DOM order
            for nt in nested:
                nt_hp = _headings_before_element(cell, nt, heading_path)
                nk, nr = classify_table(nt)
                if nk == "data":
                    nc = parse_data_table(nt, nt_hp, doc_id, config)
                else:
                    nc = parse_layout_table(nt, nt_hp, doc_id, config)
                for c in nc:
                    c.metadata["nested_table"] = True
                    c.metadata.setdefault("table_kind", nk)
                    c.metadata["classification_reason"] = nr
                chunks.extend(nc)

            # Non-table remnants in the cell
            remnant = _extract_non_table_content(cell)
            if remnant.strip():
                role = _guess_region_role(cell, remnant)
                chunks.append(_layout_region(cell_hp, remnant, cell, ci, role, doc_id))
        else:
            text = _tag_text(cell)
            if not text.strip():
                continue
            role = _guess_region_role(cell, text)
            chunks.append(_layout_region(cell_hp, text, cell, ci, role, doc_id))

    return chunks


def _layout_region(
    hp: list[str],
    text: str,
    cell: Tag,
    cell_idx: int,
    role: str,
    doc_id: str,
) -> Chunk:
    prefix = _heading_prefix(hp)
    embed = f"{prefix}\n\n{text}".strip() if prefix else text
    return Chunk(
        chunk_id=f"{doc_id}_{_uid()}",
        doc_id=doc_id,
        chunk_type="layout_region",
        heading_path=hp,
        embedding_text=embed,
        cleaned_html=_tag_html(cell),
        plain_text=text,
        metadata={
            "block_types": ["layout_cell"],
            "table_kind": "layout",
            "region_role": role,
            "cell_index": cell_idx,
            "token_estimate": estimate_tokens(text),
            "dom_path": _dom_path(cell),
        },
    )


def _detect_cell_headings(cell: Tag, parent_hp: list[str]) -> list[str]:
    """Build heading_path for a layout cell.

    Starts from the parent heading_path, then appends any headings
    found **inside** this cell.
    """
    hp = list(parent_hp)
    for h in cell.find_all(list(HEADING_TAGS)):
        lvl = _heading_level(h.name)
        txt = _tag_text(h)
        if txt:
            # trim to level
            while hp:
                existing_lvl = int(hp[-1][2]) if len(hp[-1]) > 2 and hp[-1][1] == "H" and hp[-1][2].isdigit() else 0
                if existing_lvl >= lvl:
                    hp.pop()
                else:
                    break
            hp.append(f"[H{lvl}] {txt}")
    return hp


def _headings_before_element(cell: Tag, target: Tag, parent_hp: list[str]) -> list[str]:
    """Collect headings inside *cell* that appear before *target* in DOM order.

    Used to build the heading_path for a nested table so that headings
    like ``<h2>Products</h2>`` appearing before the table are included.
    """
    hp = list(parent_hp)
    for el in cell.descendants:
        if el is target:
            break
        if isinstance(el, Tag) and el.name in HEADING_TAGS:
            lvl = _heading_level(el.name)
            txt = _tag_text(el)
            if txt:
                while hp:
                    existing_lvl = int(hp[-1][2]) if len(hp[-1]) > 2 and hp[-1][1] == "H" and hp[-1][2].isdigit() else 0
                    if existing_lvl >= lvl:
                        hp.pop()
                    else:
                        break
                hp.append(f"[H{lvl}] {txt}")
    return hp


def _extract_non_table_content(cell: Tag) -> str:
    """Get text from a cell excluding nested <table> subtrees."""
    parts: list[str] = []
    for child in cell.children:
        if isinstance(child, Tag) and child.name == "table":
            continue
        if isinstance(child, Tag):
            parts.append(_tag_text(child))
        elif isinstance(child, NavigableString):
            t = str(child).strip()
            if t:
                parts.append(t)
    return " ".join(p for p in parts if p)


def _guess_region_role(cell: Tag, text: str) -> str:
    """Heuristic region role: nav | aside | main | boilerplate | unknown."""
    links = cell.find_all("a", recursive=True)
    link_len = sum(len(_tag_text(a)) for a in links)
    ld = link_len / max(len(text), 1)

    if ld > 0.6 and len(links) >= 3:
        avg = link_len / max(len(links), 1)
        return "nav" if avg < 30 else "boilerplate"

    if len(text) < 30:
        return "boilerplate"

    if cell.find(list(HEADING_TAGS)) or len(text) > 200:
        return "main"

    if cell.find_all("img", recursive=True) and len(text) < 100:
        return "aside"

    return "unknown"


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  10. Public Entry Point
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


def chunk_froala_html(
    html_str: str,
    doc_id: str,
    config: ParseConfig | None = None,
) -> list[Chunk]:
    """Parse Froala 3.2.0 HTML and produce RAG-ready chunks.

    This is the single public entry point.
    """
    if config is None:
        config = ParseConfig()

    soup = sanitize_and_normalize_html(html_str)
    soup = normalize_froala_structure(soup)

    root = soup.find("div", id="_root") or soup.find("div") or soup
    hs: dict[str, list] = {"path": [], "levels": []}
    blocks = extract_blocks(root, hs, config)

    chunks = chunk_sections(blocks, doc_id, config)

    for i, c in enumerate(chunks):
        c.metadata.setdefault("source_order", i)

    return chunks


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  11. Pretty-print helper
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


def print_chunks(chunks: list[Chunk], *, max_embed: int = 250) -> None:
    """Debug printer."""
    print(f"\n{'=' * 72}")
    print(f"  Total chunks: {len(chunks)}")
    print(f"{'=' * 72}")
    for i, c in enumerate(chunks):
        ep = c.embedding_text[:max_embed]
        if len(c.embedding_text) > max_embed:
            ep += "…"
        print(f"\n─── Chunk {i} ───")
        print(f"  type:         {c.chunk_type}")
        print(f"  heading_path: {c.heading_path}")
        print(f"  tokens (est): {c.metadata.get('token_estimate', '?')}")
        for k in ("table_kind", "table_confidence", "region_role", "row_index", "block_types", "dom_path"):
            if k in c.metadata:
                val = c.metadata[k]
                if k == "dom_path" and isinstance(val, list):
                    val = val[:2]
                print(f"  {k}: {val}")
        print(f"  embedding_text:\n    {ep}")
    print()


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  12. Test Samples
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SAMPLE_1 = """
<h1>프로젝트 보고서</h1>
<h2>개요</h2>
<p>본 보고서는 2024년 1분기 프로젝트 현황을 요약합니다.</p>
<p>주요 성과는 다음과 같습니다:</p>
<ul>
  <li>매출 15% 증가</li>
  <li>신규 고객 200명 확보</li>
  <li>시스템 안정성 99.9% 달성</li>
</ul>
<h2>매출 분석</h2>
<p>1분기 총 매출은 50억원으로, 전년 동기 대비 15% 증가하였습니다.</p>
<h3>지역별 현황</h3>
<p>수도권 매출이 전체의 60%를 차지합니다.</p>
"""

SAMPLE_2 = """
<table role="presentation" width="100%">
  <tr>
    <td width="200" valign="top">
      <h3>메뉴</h3>
      <a href="/home">홈</a><br>
      <a href="/about">회사소개</a><br>
      <a href="/products">제품</a><br>
      <a href="/contact">연락처</a><br>
      <a href="/support">고객지원</a>
    </td>
    <td valign="top">
      <h1>제품 소개</h1>
      <p>당사의 주력 제품을 소개합니다. 모든 제품은 ISO 9001 인증을 받았습니다.</p>
      <h2>주력 제품 라인업</h2>
      <p>2024년 신제품 3종이 출시되었으며, 고객 만족도가 매우 높습니다.</p>
      <table>
        <caption>2024년 신제품 목록</caption>
        <thead>
          <tr><th>제품명</th><th>가격</th><th>출시일</th><th>평점</th></tr>
        </thead>
        <tbody>
          <tr><td>Alpha Pro</td><td>99,000원</td><td>2024-01</td><td>4.8</td></tr>
          <tr><td>Beta Max</td><td>149,000원</td><td>2024-03</td><td>4.6</td></tr>
          <tr><td>Gamma Lite</td><td>59,000원</td><td>2024-02</td><td>4.9</td></tr>
        </tbody>
      </table>
      <p>자세한 내용은 각 제품 페이지를 참고하세요.</p>
    </td>
  </tr>
</table>
"""

SAMPLE_3 = """
<h1>매출 보고서</h1>
<h2>월별 매출 현황</h2>
<p>아래 표는 2024년 상반기 월별 매출 데이터입니다.</p>
<table>
  <caption>2024년 상반기 월별 매출</caption>
  <thead>
    <tr>
      <th scope="col">월</th>
      <th scope="col">매출(억원)</th>
      <th scope="col">전년비</th>
      <th scope="col">목표달성률</th>
    </tr>
  </thead>
  <tbody>
    <tr><td>1월</td><td>8.2</td><td>+12%</td><td>102%</td></tr>
    <tr><td>2월</td><td>7.5</td><td>+8%</td><td>95%</td></tr>
    <tr><td>3월</td><td>9.1</td><td>+15%</td><td>110%</td></tr>
    <tr><td>4월</td><td>8.8</td><td>+10%</td><td>105%</td></tr>
    <tr><td>5월</td><td>9.5</td><td>+18%</td><td>115%</td></tr>
    <tr><td>6월</td><td>10.2</td><td>+22%</td><td>120%</td></tr>
  </tbody>
</table>
<p>6월 매출이 최고치를 기록하였으며, 하반기 전망도 긍정적입니다.</p>
"""

SAMPLE_4 = """
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Froala 문서</title>
  <style>body { font-family: Arial; }</style>
  <script>console.log('test');</script>
</head>
<body>
  <h1>Froala 에디터 문서</h1>
  <p>이 문서는 Froala Editor 3.2.0의 fullPage 모드로 작성되었습니다.</p>
  <h2>주요 기능</h2>
  <p>WYSIWYG 편집, 이미지 삽입, 표 작성 등을 지원합니다.</p>
  <p>HTML5 표준을 준수하며, 반응형 레이아웃을 기본 지원합니다.</p>
  <noscript>JavaScript를 활성화하세요.</noscript>
  <template><div>템플릿 내용</div></template>
</body>
</html>
"""

SAMPLE_5 = """
<div>
첫 번째 문단입니다. 여기서 중요한 내용을 설명합니다.<br><br>
두 번째 문단입니다. 앞서 언급한 내용에 대해 추가 설명을 합니다.<br><br>
세 번째 문단입니다. 결론적으로 이 프로젝트는 성공적이었습니다.<br>
이것은 같은 문단의 다음 줄입니다.
</div>
"""

SAMPLE_6 = """
<h1>깨진 HTML
<p>닫히지 않은 태그들
<div><span>중첩 문제<p>여기서 끊김</div></span>
<table>
<tr><td>셀1<td>셀2
<tr><td>셀3<td>셀4
</table>
<h2>그래도 동작해야 함</h2>
<p>파서가 malformed HTML을 어느 정도 복구해야 합니다.</p>
"""


def main() -> None:
    """Run all 6 sample tests and pretty-print results."""
    samples = [
        ("Sample 1: Heading + P + UL", SAMPLE_1),
        ("Sample 2: Layout table (nav + nested data table)", SAMPLE_2),
        ("Sample 3: Pure data table", SAMPLE_3),
        ("Sample 4: Froala fullPage HTML", SAMPLE_4),
        ("Sample 5: BR-based paragraphs", SAMPLE_5),
        ("Sample 6: Malformed HTML", SAMPLE_6),
    ]

    for title, html_str in samples:
        print(f"\n{'#' * 72}")
        print(f"# {title}")
        print(f"{'#' * 72}")
        chunks = chunk_froala_html(html_str, doc_id="test_doc")
        print_chunks(chunks)

        types: dict[str, int] = {}
        for c in chunks:
            types[c.chunk_type] = types.get(c.chunk_type, 0) + 1
        print(f"  ▸ type distribution: {types}")


if __name__ == "__main__":
    main()
